name: badges
description: A package for creating badges. Badges can be used for an additional marker for any widget, e.g. show a number of items in a shopping cart.
version: 3.0.2
repository: https://github.com/yako-dev/flutter_badges
issue_tracker: https://github.com/yako-dev/flutter_badges/issues

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=0.2.5"

screenshots:
  - description: "Shopping cart with badge for pub.dev preview"
    path: images/pub_dev_preview.png
