name: badges
description: A flutter package for creating badges. Badges can be used for an additional marker for any widget, e.g. show a number of items in a shopping cart.
version: 1.1.5
homepage: https://github.com/yadaniyil/flutter_badges

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=0.2.5 <2.0.0"
